on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Build the index.html file
        run: python build.py

      - name: Upload files to pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: out/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  
  name: Lint

  on: # yamllint disable-line rule:truthy
    push: null
    pull_request: null

  permissions: {}

  jobs:
    build:
      name: Lint
      runs-on: ubuntu-latest

      permissions:
        contents: read
        packages: read
        # To report GitHub Actions status checks
        statuses: write

      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            # super-linter needs the full git history to get the
            # list of files that changed across commits
            fetch-depth: 0

        - name: Super-linter
          uses: super-linter/super-linter@v7.2.0 # x-release-please-version
          env:
            # To report GitHub Actions status checks
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}